# Generated by Django 5.0.1 on 2024-01-17 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devtool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('image', models.ImageField(blank=True, upload_to='idea/%Y%m%d', verbose_name='이미지')),
                ('content', models.TextField(verbose_name='아이디어 설명')),
                ('interest', models.IntegerField(default=0, verbose_name='아이디어 관심도')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devtool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devtool.devtool', verbose_name='예상 개발툴')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ideastar', to='idea.idea')),
            ],
        ),
    ]
