# Generated by Django 5.0.1 on 2024-01-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_idea_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.TextField(verbose_name='아이디어 설명'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='interest',
            field=models.IntegerField(default=0, verbose_name='아이디어 관심도'),
        ),
    ]
